#include <QString>
#ifndef QUERIES_H
#define QUERIES_H

QString table_creation_text =
        "CREATE TABLE Caretaker ("
        "    caretaker_id INTEGER PRIMARY KEY,"
        "    full_name TEXT CHECK (full_name != ''),"
        "    phone_number TEXT CHECK (phone_number != ''),"
        "    date_of_birth TEXT CHECK (date_of_birth != '')"
        ");"
        ""
        "CREATE TABLE Veterinarian ("
        "    veterinarian_id INTEGER PRIMARY KEY,"
        "    full_name TEXT CHECK (full_name != ''),"
        "    phone_number TEXT CHECK (phone_number != ''),"
        "    date_of_birth TEXT CHECK (date_of_birth != '')"
        ");"
        ""
        "CREATE TABLE LivingArea ("
        "    living_area_id INTEGER PRIMARY KEY,"
        "    living_area_name TEXT CHECK (living_area_name != ''),"
        "    living_area_charactetistic TEXT CHECK (living_area_charactetistic != '')"
        ");"
        ""
        "CREATE TABLE Ration ("
        "    ration_id INTEGER PRIMARY KEY,"
        "    ration_name TEXT CHECK (ration_name != '')"
        ");"
        ""
        "CREATE TABLE RationType ("
        "    ration_type_id INTEGER PRIMARY KEY,"
        "    ration_type_name TEXT CHECK (ration_type_name != '')"
        ");"
        ""
        "CREATE TABLE Mammal ("
        "    mammal_id INTEGER PRIMARY KEY,"
        "    identifier TEXT CHECK(identifier !=''),"
        "    name TEXT CHECK(name != ''),"
        "    age INTEGER CHECK(age >= 0 AND age < 100),"
        "    sex TEXT CHECK (sex != ''),"
        "    fk_l_a_id INTEGER,"
        "    fk_c_id INTEGER,"
        "    fk_v_id INTEGER,"
        "    fk_r_n_id INTEGER,"
        "    fk_r_t_id INTEGER,"
        "    FOREIGN KEY ( fk_l_a_id )"
        "      REFERENCES LivingArea ( living_area_id ),"
        "    FOREIGN KEY ( fk_c_id )"
        "      REFERENCES Caretaker ( caretaker_id ),"
        "    FOREIGN KEY ( fk_v_id )"
        "      REFERENCES Veterinarian ( veterinarian_id ),"
        "    FOREIGN KEY ( fk_r_n_id )"
        "      REFERENCES Ration ( ration_id ),"
        "    FOREIGN KEY ( fk_r_t_id )"
        "      REFERENCES Ration ( ration_type_id )"
        ");"
        ""
        "CREATE TABLE Bird ("
        "    bird_id INTEGER PRIMARY KEY,"
        "    identifier TEXT CHECK(identifier !=''),"
        "    name TEXT CHECK(name != ''),"
        "    age INTEGER CHECK(age >= 0 AND age < 100),"
        "    sex TEXT CHECK (sex != ''),"
        "    country_code TEXT CHECK(country_code != ''),"
        "    country_name TEXT CHECK(country_name != ''),"
        "    start_date TEXT CHECK(start_date != ''),"
        "    end_date TEXT CHECK(end_date != ''),"
        "    fk_l_a_id INTEGER,"
        "    fk_c_id INTEGER,"
        "    fk_v_id INTEGER,"
        "    fk_r_n_id INTEGER,"
        "    fk_r_t_id INTEGER,"
        "    FOREIGN KEY ( fk_l_a_id ) "
        "      REFERENCES LivingArea ( living_area_id ),"
        "    FOREIGN KEY ( fk_c_id ) "
        "      REFERENCES Caretaker ( caretaker_id ),"
        "    FOREIGN KEY ( fk_v_id ) "
        "      REFERENCES Veterinarian ( veterinarian_id ),"
        "    FOREIGN KEY ( fk_r_n_id ) "
        "      REFERENCES Ration ( ration_id ),"
        "    FOREIGN KEY ( fk_r_t_id ) "
        "      REFERENCES Ration ( ration_type_id )"
        ");"
        ""
        "CREATE TABLE Reptile ("
        "    reptile_id INTEGER PRIMARY KEY,"
        "    identifier TEXT CHECK(identifier !=''),"
        "    name TEXT CHECK(name != ''),"
        "    age INTEGER CHECK(age >= 0 AND age < 100),"
        "    sex TEXT CHECK (sex != ''),"
        "    avarage_temperature TEXT CHECK (avarage_temperature != ''),"
        "    wintering_start_date TEXT CHECK (wintering_start_date !=''),"
        "    wintering_end_date TEXT CHECK (wintering_end_date !=''),"
        "    fk_l_a_id INTEGER,"
        "    fk_c_id INTEGER,"
        "    fk_v_id INTEGER,"
        "    fk_r_n_id INTEGER,"
        "    fk_r_t_id INTEGER,"
        "    FOREIGN KEY ( fk_l_a_id ) "
        "      REFERENCES LivingArea ( living_area_id ),"
        "    FOREIGN KEY ( fk_c_id ) "
        "      REFERENCES Caretaker ( caretaker_id ),"
        "    FOREIGN KEY ( fk_v_id ) "
        "      REFERENCES Veterinarian ( veterinarian_id ),"
        "    FOREIGN KEY ( fk_r_n_id ) "
        "      REFERENCES Ration ( ration_id ),"
        "    FOREIGN KEY ( fk_r_t_id ) "
        "      REFERENCES Ration ( ration_type_id )"
        ");";

QString fill_ration_text = "";

QString fill_ration_type_text = "";

QString fill_living_area_text = "";

#endif // QUERIES_H
